services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    ports:
      - "3000:3000"

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    ports:
      - "80:80"

    restart: unless-stopped