services:
  manageus-backend:
    build:
      context: ./backend
      dockerfile: DockerFile.dev

    ports:
      - "3000:3000"

    volumes:
      - ./backend:/app
      - /app/node_modules

  manageus-frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile.dev

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules