services:
  manageus-backend:
    build:
      context: ./backend
      dockerfile: DockerFile.prod
    container_name: "manageus-api"

    networks:
      - default
      - proxy-net

    restart: unless-stopped

  manageus-frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile.prod
    
    container_name: "manageus"

    networks:
      - default
      - proxy-net

    restart: unless-stopped

networks:
  proxy-net:
    external: true
  default:
    driver: bridge